### ISSUE TITLE
No clear style for multimethods

### ISSUE THREAD

**Issue by marknsikora** [bbatsov/clojure-style-guide#106]
Where to put the `dispatch-val` for a multimethod is not covered by the style guide. Personally I see a few solutions.

```clojure
(defmulti example keyword)

(defmethod example
  :foo [c]
  :a-foo)

(defmethod example :bar
  [c]
  :a-bar)

(defmethod example
  :baz
  [c]
  :a-baz)
```

Personally I'm in favour of the `bar` example. But I will yield to the judgment of the clojure community.

**Comment by arrdem** [comment]
As with the `defn` form, I think that the arguments belong on the following line. However as the dispatch value is intentionally part of the name of the subsequent `fn`, I think that the dispatch value should if reasonable be on the same line as the name and `defmethod`. So yes I'd argue for `:bar`.

**Comment by bbatsov** [comment]
:+1: for the `:bar` style.

**Comment by kgann** [comment]
:+1: for `:bar`

**Comment by gws** [comment]
:+1: for `bar`

**Comment by bbatsov** [comment]
Seems there's a consensus. @marknsikora You can convert your suggestion to a rule.
