### ISSUE TITLE
-> versus . when using records

### ISSUE THREAD

**Issue by dyba** [bbatsov/clojure-style-guide#108]
I'd like to hear the reasons behind choosing a particular way of populating a record.

``` clojure
(defrecord Example [name] [value])

(Example. "hello" "world")
(->Example "hello" "world")
```

I think it makes more sense to use the ```.``` notation because it makes it evident that we're working with a Java class that ```defrecord``` generates. Using the ```->RecordName``` approach makes me think twice: "Did the developer leave a typo here and intend this to mean thread RecordName, (i.e. did they intend to use the threading macro)?"

What are the community's thoughts?

**Comment by arrdem** [comment]
The `-.` is AFAIK reader and evaluator shugar for invoking a raw Java class ctor whereas the `->` seems to be the convention for an abstract constructor which may perform arbitrary computation and return a "new" datum. In the various datastructure libraries I've built, `->` constructors have been present even when there is not "truly" a backing Java class being instantiated. Furthermore the `->` constructor is a `IFn` where the `-.` is not meaning that it is possible to map or fold a `->` constructor where a `#(Foo. %1)` would be required to map or fold a class ctor special form.

**Comment by dyba** [comment]
How silly of me; I should have read the documentation beforehand. It turns out that ```->TypeName``` is a generated function provided by ```defrecord```. I knew that ```defrecord``` created compiled bytecode of a Java class with the same name as that which is given to ```defrecord```, hence my confusion of whether to populate a new record with the ```.``` operator. But the source code and docs made it crystal clear. While you can populate new records by using ```TypeName.```, you wouldn't want to do it that way because the ```->TypeName``` function has been provided for you. So when using ```defrecord```, stick to using ```->TypeName```, plain and simple.
