### ISSUE TITLE
Proposal: Sort arities from fewest to most

### ISSUE THREAD

**Issue by arrdem** [bbatsov/clojure-style-guide#109]
so

```Clojure
(fn ([x] ...) ([x y] ...) ([x y z & more] ...))
```

Since the common case of multiple arity functions is that you have several partial application arities, one "full" arity and then a varargs case which is a foldr over the varargs. This is also in keeping with the style clojure.core uses for such functions.

**Comment by bbatsov** [comment]
No arguing about this. PR welcome.
