### ISSUE TITLE
Add rationale

### ISSUE THREAD

**Issue by vendethiel** [bbatsov/clojure-style-guide#111]
In a lot of places here, there's a rule (say: "avoid ref-set and use alter instead") but no explanation is given as to **why** the former needs to be avoided. This happens in several places. I'd really enjoy knowing why it's that way (a link would totally suffice)

thanks!

**Comment by bbatsov** [comment]
Yeah, I totally agree that most rules would benefit from some extended rationale. Unfortunately I'm super short on free time and others will have to help with this.
