### ISSUE TITLE
Fixing indentation of example code in docstring

### ISSUE THREAD

**Issue by rauhs** [bbatsov/clojure-style-guide#117]
Having a doc string with example code that spans over multiple lines and needs indentation is not properly formatted due to clojure removing any leading whitespace on each line:

```
(defn ex
  "foo
   (let [x '10]
     (+ x 10)"
  [])
```

Multiple solutions can be proposed:

A.
```
(defn ex
  "foo
    (let [x '10]
    ,,(+ x 10)"
  [])
```
B. 
```
(defn ex
  "foo
    (let [x '10]
    __(+ x 10)"
  [])
```
C. 
```
(defn ex
  "foo
    (let [x '10]
    ..(+ x 10)"
  [])
```
Or simply prefixing the lines:

D.
```
(defn ex
  "foo
   | (let [x '10]
   |   (+ x 10)"
  [])
```
E.
```
(defn ex
  "foo
   > (let [x '10]
   >   (+ x 10)"
  [])
```

Any thoughts what should be recommended? I personally like D (and also E).

**Comment by arrdem** [comment]
While I think that `d` and `e` are acceptable workarounds to the non-problem of `clojure-mode` enforcing indentation in docstrings, I think that from any sort of a coding convention standpoint they don't really make sense. Many existing libraries make use of Markdown formatting in their docstrings including trippletick example blocks, and I see no good reason why we should introduce another pseudo-standard to work around a missbehaving Emacs library.

**Comment by rauhs** [comment]
Makes sense. I forgot this was stripped by the editors. (Cursive also does this).
