### ISSUE TITLE
What's the reasoning behind io! ?

### ISSUE THREAD

**Issue by didibus** [bbatsov/clojure-style-guide#120]
I'd like to know what's the reasoning and where are the references behind the: https://github.com/bbatsov/clojure-style-guide#refs-io-macro

It sounds like a good idea to me, but it's not used once in the standard library, and never used inside clojure.java.io.

**Comment by bbatsov** [comment]
A transaction might be restarted multiple times, so any `io` there would be problematic. See http://conj.io/store/v1/org.clojure/clojure/1.7.0/clj/clojure.core/io%21/ for examples
