### ISSUE TITLE
Changes for ebook versions

### ISSUE THREAD

**Issue by oubiwann** [bbatsov/clojure-style-guide#123]
I've forked the repo and made changes to it that provide for a better experience in ebooks (as well as HTML and PDF versions). This did require some changes to the source document.

If you are interested in having the changes merged back into your project, I will create a PR.

Here's the fork, for your review:
- https://github.com/oubiwann/clojure-style-guide

Thanks for taking the time to create such a great resource for the community!

**Comment by bbatsov** [comment]
I'd definitely would mind having something like this upstream. I'm mostly worried about the change dropping all the newlines as this makes it harder to edit the source (and to read it). I'm surprised the export the ebook formats treats them as hard line-breaks (as they are not the treated this way by markdown).

**Comment by oubiwann** [comment]
Yeah, I was pretty bummed about the newline thing. I was rather suprised, since pandoc explicitly supports Github markdown. I'll look into it some more and see if someone has a work-around.

**Comment by rbf** [comment]
This is maybe related to the fact that [GFM](https://help.github.com/articles/github-flavored-markdown/) [_treats newlines in paragraph-like content as real line breaks, which is usually what you intended_](https://help.github.com/articles/writing-on-github/#newlines). How does it render assuming normal Markdown?

**Comment by bbatsov** [comment]
Any progress here?

**Comment by bbatsov** [comment]
Since this ticket was create I've converted the guide to AsciiDoc, changed it's layout completely (I think for the better) and published it to https://guide.clojure.style
