### ISSUE TITLE
Formatter and style checker for Cursive and Emacs

### ISSUE THREAD

**Issue by adam-arold** [bbatsov/clojure-style-guide#127]
Do you plan to add formatter and style checker configs/plugins for the tools which are commonly used for Clojure development? Maybe this is just enterprise thinking on my part but I think it would be useful.

**Comment by agarman** [comment]
Plugins:
[lein-cljfmt](https://github.com/weavejester/cljfmt)
[lein-zprint](https://github.com/kkinnear/lein-zprint)
[boot-fmt](https://github.com/pesterhazy/boot-fmt)

Editors:
[reformat in Cider](http://stackoverflow.com/questions/11423566/how-do-i-intelligently-re-indent-clojure-in-emacs)
[reformat in Cursive](https://cursive-ide.com/userguide/formatting.html)

**Comment by bbatsov** [comment]
See also https://guide.clojure.style/#code-formatters
