### ISSUE TITLE
Comment Annotations

### ISSUE THREAD

**Issue by cloojure** [bbatsov/clojure-style-guide#130]
Very nice summary of clojure style!  I have one possible enhancement for you.

I have developed a style for annotating code where I just prepend a # symbol to the annotation.  This makes searching easy since the symbols are very unique, and it is easier to type since you don't have to turn caps-lock on & off.  Examples:

```
; #todo add more unit tests
; #fixme this crashes occasionally...
; #awt #todo For some comments I also add my initials (#awt) so it is even easier to search or grep 
```

Tools like IntelliJ seem to already recognize this notation, and it is also very easy to find using either grep on the command line or using the 'find' function in an editor.

**Comment by arrdem** [comment]
I don't personally think this makes sense as part of this style guide. There are many many variations of `TODO:`, `FIXME:`, `HACK:` etc which already exist in Clojure comments and in other languages. Some have editor support, some don't. As Clojure doesn't have language support for `#todo` as some sort of noop tag (nor do I think such support would make sense) I think this style is inappropriate to a guide which attempts to reflect broader notions of "good style".

**Comment by cloojure** [comment]
Since the annotations are purely a commenting convention, I suppose one could argue that it is too subjective to include in a coding style guide.  Is that what you meant?

I think the basic idea is to differentiate between "permanent" comments and those that represent a "work-in-progress" part of the code.

**Comment by bbatsov** [comment]
I close this ticket, as I tend to agree with @arrdem, plus no one voiced thier supposed to broaden the existing definition. When it comes to style I think that less (in terms of guidelines and ambiguity) is always more. :-)
