### ISSUE TITLE
Add standard for naming tests

### ISSUE THREAD

**Issue by lvh** [bbatsov/clojure-style-guide#131]
I have seen some conflicting ways of naming Clojure tests:

- `(deftest xyzzy-test ...)`
- `(deftest xyzzy-tests ...)`
- `(deftest xyzzy ...)`
- `(deftest test-xyzzy ...)`

Clojure test namespaces seem to be fairly consistent: `project.xyzzy-test`. I think the first form is most idiomatic, but I came to the Clojure style guide for advice, and it didn't appear to have an opinion on this yet.

**Comment by bbatsov** [comment]
Yeah, it would be nice to add some advice regarding this. Probably something about test namespaces as well, as some people don't use the common convention. 

Typically I use `xyzzy-test`, but I'd like to hear what others are doing.

**Comment by bbatsov** [comment]
P.S. In general it'd be nice for us to document all best practices related to `clojure.test`. Not sure if someone would like to tackle this, as I'm a bit too busy these days.

**Comment by holguinj** [comment]
I don't know if I've ever seen `test-xyzzy` in the wild. In my organization, `xyzzy-test` is overwhelmingly common, and I think that works pretty well.

**Comment by danielcompton** [comment]
*-test is what we use and the most common one I've seen.

**Comment by arrdem** [comment]
I suppose there's an argument to be made that this convention is strictly advisory. The whole idea of namespacing is to try and eliminate prefix and postfix conventions with an explicit qualification, so in the context of a `-test` namespace anything should go.

**Comment by bbatsov** [comment]
True. I'm guessing most people prefix/suffix the names, so it's easier for them to find them when they search for them.

**Comment by lvh** [comment]
That's true, but "strictly advisory" seems like a property true of most parts of the style guide, it being a style guide after all ;)
