### ISSUE TITLE
Should predicate-like kw args end with questionmark

### ISSUE THREAD

**Issue by sbelak** [bbatsov/clojure-style-guide#136]
``` clojure
(foo {:fluffy? true} xs)
```

vs.

``` clojure
(foo {:fluffy true} xs)
```

clojure.core seems to adhere to the later (see `spec/map-of`, `core.server/start-server`), but a lot of libraries (random example https://github.com/ztellman/aleph/blob/f540bb101299448cd3f867f9b0172f5c12acd535/src/aleph/http.clj#L20) use the former.

**Comment by maxcountryman** [comment]
Aleph also uses boolean-containing vars [formatted in this way](https://github.com/ztellman/aleph/blob/2ba3484ead3a8443667d3a3caddf9739c6841d9c/src/aleph/netty.clj#L312).

```clj
(when fluffy? :aww)
```

I personally find this much easier to read.

**Comment by bbatsov** [comment]
I'll close this ticket in favour of #182, that generated a bigger conversation on the subject.
