### ISSUE TITLE
Trailing parentheses on a single line

### ISSUE THREAD

**Issue by LukasRychtecky** [bbatsov/clojure-style-guide#138]
Hi there,

I find "Place all trailing parentheses on a single line instead of distinct lines." pretty impractical, see example below:

``` clojure
(def foo
  {:a 0
   :b 1})
```

When a pair is added to the end it leads to a messy diff. Because two lines has been changed instead of one. Wouldn't be better use this formatting?

``` clojure
(def foo
  {
   :a 0
   :b 1
  })
```

or

``` clojure
(def foo {
  :a 0
  :b 1
  })
```

What do you think? Thanks

**Comment by arrdem** [comment]
The style guide and the LISP tradition concur that collecting terminators on a single line is preferred to either single line per delimiter (Java/C style) or what you propose above.

There are many fine tools such as cljfmt, smartparens, parnifer and others all of which operate on or enforce this assumption that delimiters are trailing and gathered on one line.

I personally read Clojure by scanning by indentation ala Python and counting closing delimiters when I have to. A single line of easily understood diff noise is absolutely worth conforming with the rest of the community and your tools.

**Comment by bostonaholic** [comment]
I would choose to optimize for the reading of code over the optimization of reading a diff.
