### ISSUE TITLE
Is there a way to enforce this clojure style guide on a clojure project?

### ISSUE THREAD

**Issue by adam-arold** [bbatsov/clojure-style-guide#140]
I come from a Java background and I'm looking for a tool like checkstyle. Sorry if this question is inappropriate but I'm a bit puzzled.

**Comment by skadinyo** [comment]
Try kibit https://github.com/jonase/kibit. It doesn't enforce sytle guide, but it can analyze static code and apply the proposed change.
I don't know if there is collaboration between this style guide and kibit, but i think kibit is cool.

**Comment by arrdem** [comment]
Weavejester's lein-cljfmt can automatically impose most of the code formatting specifications described here. Where the two differ, and I can't name any differences offhand, those are improvements which should be made in lein-cljfmt.

**Comment by shaunstripe** [comment]
@bbatsov wrote RuboCop to enforce the Ruby Style Guide in projects.  A linter like this for the Clojure Style Guide would be great too

**Comment by bbatsov** [comment]
True. I actually planned to write a similar lint tool for Clojure, but I never managed to find the time for this.

**Comment by pesterhazy** [comment]
With this goal in mind, I started [boot-fmt](https://github.com/pesterhazy/boot-fmt) which, despite the name, works with leiningen-based projects just fine. It's built on the excellent zprint. Use `--options '{:style :community}` to select the style rules proposed in this guide.

Also check out https://github.com/kkinnear/lein-zprint. `zprint` is more powerful and more configurable than the above-mentioned cljfmt.

**Comment by bbatsov** [comment]
@pesterhazy It's be nice if you mentioned those tools in the style guide, so people would know how to easily apply it to their codebases.

**Comment by pesterhazy** [comment]
@bbatsov, do you mean I should mention clojure-style-guide in boot-fmt's readme, or submit a PR to clojure-style-guide that mentions different options for auto-formatting code?

**Comment by bbatsov** [comment]
I guess it'd be best to do both. :-)

**Comment by pesterhazy** [comment]
@bbatsov I've added a section on the Community Style Guide in the boot-fmt docs: https://github.com/pesterhazy/boot-fmt#configuration

**Comment by bbatsov** [comment]
Thanks! Btw, it's Emacs, not EMACS. :-)

**Comment by pesterhazy** [comment]
Whoops, mea culpa. Fixed!

**Comment by bbatsov** [comment]
I've added some notes here https://guide.clojure.style/#tools Feel free to extend them.
