### ISSUE TITLE
Unclear what this means: Use one file per namespace.

### ISSUE THREAD

**Issue by didibus** [bbatsov/clojure-style-guide#145]
Hi,

The guide says: `Use one file per namespace.`, but I'm unclear if this means don't have more than one namespace per file, or if it means don't break a namespace over multiple files?

**Comment by agarman** [comment]
@didibus - here are examples:
``` 
;; file foo.clj
(ns foo)
(ns bar) ;; BAD
```

```
;; file foo.clj
(ns foo)
---
;; file more.clj
(ns more)
(ns foo) ;; BAD
```

`Use one file per namespace.` is correct as having multiple `ns` in a file is bad style **AND** having a `namespace` defined across multiple files is **also** bad style.

**Comment by lxsli** [comment]
Perhaps `Use exactly one file per namespace.`
