### ISSUE TITLE
Rule around newline placement in fn calls?

### ISSUE THREAD

**Issue by vemv** [bbatsov/clojure-style-guide#162]
Say a function call would be too long so span a single line, so we decide to place some newlines.

There are at least two styles:

```
(release-sharks
 :fooooooo
 :barrrrrr
 :bazzzzzz)
 ```
 
 and
 
 ```
(release-sharks :fooooooo
                 :barrrrrr
                 :bazzzzzz)
```

...that is, 'newline-after-fn', and 'newline-after-first-arg'.

I'd advocate that, generally, the latter should be strongly preferred. Common sense can dictate exceptions, otherwise newline-after-fn should be discouraged?

#### Example 1

```
(release-sharks
 :fooooooo
 :barrrrrr
 :bazzzzzz)
```

This reads vertically. Humans are used to read horizontally.

The better alternative:

```
(release-sharks :fooooooo
                :barrrrrr
                :bazzzzzz)
```

has some verticality, but at least for a while the code could be read like a sentence, so I could begin reading the code with the correct context set in my brain ("this is a function call, and not data").

#### Example 2

```
(some.quite.long.namespace/a-very-long-fn-name
 :fooooooo
 :barrrrrrrr)
```

This reads like a zigzag: when my eye is reading `...fn-name`, it has to suddenly jump a lot to the left.

It wouldn't surprise me if that contributes to eye strain.

---

In general, as a rule of thumb I'd say that code should be laid out these ways, from better to worse:

- horizontally
- like stairs: left-to-right, downward, (recur)
- like a column: vertically
- like a zigzag

**Comment by vemv** [comment]
This is partly, just my opinion, but also the way lots of Clojure code is laid out I think?

I hope there is strong evidence for my point (beyond some reasoning).

WDYT?

**Comment by vemv** [comment]
It is also worth noting that 1-space indentation is generally used in multi-line fn-calls.

So, in the example

```
(release-sharks
 :fooooooo
 :barrrrrr
 :bazzzzzz)
```

there's almost no visual distinction between fn and args, so the fn call doesn't look like a fn call anymore: it looks like a list.

**Comment by bbatsov** [comment]
Oh, I didn't see this ticket for quite a while - sorry about that!

I've noticed that most people (including me) use the two styles interchangeably. Generally I use the wider formatting when I can and fold the narrow version if I need to reduce the line lengths somewhere. 

> This reads vertically. Humans are used to read horizontally.

Are you sure about this? I've heard the absolutely opposite as an argument in favour of shorter lines. :-)

There's also another thing to consider - when you break down a call do you put one arg on each line or as many as you can fit. I guess one might be optimal, but I've seen plenty examples of the alternative approach.

**Comment by vemv** [comment]
I can see how rules shouldn't come from a vacuum, so if in your experience there isn't that much evidence favoring my proposed rule, I should discard it :)

At least I'm happy to have written it down somewhere.
