### ISSUE TITLE
Standard naming for namespace argument

### ISSUE THREAD

**Issue by garrett-hopper** [bbatsov/clojure-style-guide#163]
I wonder what a reasonable naming convention for a namespace as an argument would be for https://github.com/bbatsov/clojure-style-guide#idiomatic-names.
`ns` makes sense, but I don't like the idea of shadowing `clojure.core/ns`. (Though admitedly `ns` would never be used inside a function.)
Perhaps `n`? What else have people seen around?

**Comment by agarman** [comment]
In `clojure.core` the standard naming convention for a namespace argument is `ns`. Shadowing `ns` has far less impact than other shadowed `Var`s from core as `ns` is usually used once per file.

**Comment by bbatsov** [comment]
I agree with @agarman. `n` generally sounds like a number to me.
