### ISSUE TITLE
How many empty lines between top-level forms?

### ISSUE THREAD

**Issue by danielcompton** [bbatsov/clojure-style-guide#170]
The rule for [top-level-forms](https://github.com/bbatsov/clojure-style-guide#empty-lines-between-top-level-forms) says:

> Use empty lines between top-level forms. An exception to the rule is the grouping of related defs together.

It doesn't say how many empty lines should be put between top level forms though. Most open source Clojure code including Clojure itself, as well as the code samples in the style guide use a single empty line between forms. Some people do use two lines though. Is this something the style guide wants to take a position on?

**Comment by bbatsov** [comment]
I think it should. As the usage of a single empty line is way more common I think we should promote it.
