### ISSUE TITLE
Published Website does not include links back to the repository

### ISSUE THREAD

**Issue by rymndhng** [bbatsov/clojure-style-guide#180]
It would be handy for the Contributing section to point back to the Github repo when viewed on https://guide.clojure.style.

**Comment by bbatsov** [comment]
That's now fixed https://guide.clojure.style/#how-to-contribute

**Comment by rymndhng** [comment]
Thank you @bbatsov! Merry Advent of Open Source :)

**Comment by bbatsov** [comment]
Thanks! 🙇
