### ISSUE TITLE
describe how to mark functions as deprecated

### ISSUE THREAD

**Issue by borkdude** [bbatsov/clojure-style-guide#181]
This is currently missing.

**Comment by bbatsov** [comment]
Yep. It's been on my todo for a while to add a section about the typical metadata. In this case it should be `:deprecated` `true` (or a string indicating the version in which a var was deprecated).

**Comment by borkdude** [comment]
Maybe we can put `:deprecated "<version>"` as the preferred way, since it's more informative?

**Comment by bbatsov** [comment]
Yep. Although keep in mind this works only for things with real releases (e.g. libraries). Many web applications won't have versions and still might want to deprecate things internally.

**Comment by hoxu** [comment]
Any thoughts on this?

There is also https://clojure.atlassian.net/browse/CLJ-706 that @puredanger last commented on in 2016-03-11.

**Comment by bbatsov** [comment]
I think it's a good idea, but I doubt it's coming any time soon. It's not that important, though, as many tools process the `:deprecated` metadata even today.

**Comment by hoxu** [comment]
@bbatsov fd5e731 :+1: 

How about mentioning the shorter version (just `^:deprecated`)?

I think at least Cursive and clj-kondo can read these.

**Comment by borkdude** [comment]
Thanks @bbatsov!

**Comment by bbatsov** [comment]
You're welcome! 

> How about mentioning the shorter version (just ^:deprecated)?

Done.

I've also added an entire section for common metadata (3 years after I promised to do so :D) https://guide.clojure.style/#common-metadata
