### ISSUE TITLE
Create a rule to have an empty line at end of file

### ISSUE THREAD

**Issue by andreolvr** [bbatsov/clojure-style-guide#190]
It's a convention and a good practice to include an empty line at the end of files, I think this styleguide should have a rule to enforce this 😃

**Comment by LukasRychtecky** [comment]
@andreolvr Never heard of it. What is it good for?

**Comment by andreolvr** [comment]
@LukasRychtecky not only a good practice, this is actually how POSIX defines a line:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
