### ISSUE TITLE
Add `comp` and `partial` style guidelines

### ISSUE THREAD

**Issue by SherSpock** [bbatsov/clojure-style-guide#191]
Currently there are no guidelines written for the `comp` and `partial` sections. These guidelines should be written to contextualize the existing examples.

PR discussion that spurred this: #184

**Comment by SherSpock** [comment]
I submit the following as a rough first pass, understanding that I may be misunderstanding the key point of the examples:

Favor `comp` over anonymous functions for function composition.
Favor `partial` over anonymous functions for currying.

**Comment by bbatsov** [comment]
Yeah, that sounds reasonable.

**Comment by SherSpock** [comment]
OK great. 

Those are in #194 as-is

**Comment by masmatsum** [comment]
> Favor `partial` over anonymous functions for currying.

You guys are probably confusing "partial application (of functions)" and "currying".
They are completely different.
`partial` does "partial application", NOT "currying".
