### ISSUE TITLE
Please use datelines on all recommendation documents.

### ISSUE THREAD

**Issue by tyohDeveloper** [bbatsov/clojure-style-guide#198]
Dateline: 2019-12-17

This is a request, not an actual question. No responses are needed.

Please, please always use a dateline for any recommendations or guides. What works in 2014 often doesn't work by 2020. This isn't so much for newsgroups. Everything here has a date tag. But anything that is intended to be a reference needs a dateline. At the top.

Here are a few examples

Dateline: 2020-01-12
Blah blah blah

Dateline: 2020-01-12 (update)
Original dateline 2014-12-31
blah blah blah

Dateline: 2014-07-07
This reference is very useful http://xxx.yyy

Dateline: 2019-11-12
Original dateline: 2010-01-15
This article has been dead for some time. Use it with extreme care.

It really helps. Things like setting up working development environment, working with node.js or other client side framework go stale quickly. One can waste a lot of time, eventually to be told, "It's dead Jim."

**Comment by bbatsov** [comment]
I get your point, but I think this will add a lot of noise. I've also never seen this done in other style guide documents. Not to mention that guidelines in Clojure don't change that often, given that Clojure itself doesn't change much. 

The guide is living document and it's constantly being updated to reflect the best practices in the Clojure community.
