### ISSUE TITLE
Consider adding :no-doc under common metadata

### ISSUE THREAD

**Issue by lread** [bbatsov/clojure-style-guide#221]
The `:no-doc` metadata is a signal to documentation tools like [Codox](https://github.com/weavejester/codox#metadata-options) and [cljdoc](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#hiding-namespaces--vars-in-documentation) that a namespace or var within a namespace should not be included as part of the public API.

If this makes sense to folks, happy to do up a PR.

**Comment by bbatsov** [comment]
PR welcome!

**Comment by lread** [comment]
Will do!
