### ISSUE TITLE
Multimethod Dispatch Val Placement advice impractical with docstring or attr-map

### ISSUE THREAD

**Issue by ryantate** [bbatsov/clojure-style-guide#228]
The [advice](https://github.com/bbatsov/clojure-style-guide#multimethod-dispatch-val-placement) "place the dispatch-val of a multimethod on the same line as the function name" in "Multimethod Dispatch Val Placement" is impractical for multimethods that are documented.

`defmulti` [requires](https://clojuredocs.org/clojure.core/defmulti) any `docstring` or `attr-map` to go in between the multimethod name and the multimethod dispatch function. For public facing multimethods (at a minimum) you are going to want to provide both of these arguments; one documents the multimethod and the other shows what arguments it takes (via `:arglists` metadata in `attr-map`).

I would suggest at minimum qualifying the advice like so:

> Place the `dispatch-val` of a multimethod on the same line as the function name (when no docstring or `attr-map` argument is provided).

Even better would be to formulate style advice for when these two or three elements must coexist. How many newlines should separate the `attr-map` from the docstring? How many should separate the `attr-map` or docstring from the dispatch function? 

I don't feel qualified to offer a suggestion. I tend to use double newlines to keep things nicely spaced and readable, but there is also something appearling about the compactness of single newlines.

**Comment by seancorfield** [comment]
`defmethod` doesn't have a docstring and that's what the guide is providing advice on. It doesn't provide any guidance for `defmulti` -- but the fact that you've raised this definitely means the guide could be clearer and perhaps _should add_ some guidance for `defmulti`?

**Comment by ryantate** [comment]
Ack, sorry. You're right, it's for `defmethod` not `defmulti.` Dispatch Val != Dispatch Func 

I'll close.
