### ISSUE TITLE
Improve title

### ISSUE THREAD

**Issue by lgrapenthin** [bbatsov/clojure-style-guide#232]
"The Clojure Style Guide" as a title projects much more authority than this document has or should have.  By using the definitive form it leaves no space for other.  It makes unsuspecting readers believe that it is some official reference to adhere to.  In sharp contrast, its introduction already clarifies that it consists of personally opinionated rules somebody assembled based on his "extensive career as a software engineer".  This is a source for much confusion.

Here are some brainstormed ideas to improve upon:
- "An unofficial Clojure Style Guide"
- "My Clojure Style Recommendations"
- "Clojure Style for extensive career"
- "Clojure with Style: Unoffical rules"

**Comment by bbatsov** [comment]
I should actually remove those first-person references as they are just a remnant of the early days of the style guide (and I'll take a note to do so). I think the name is fine as it is - it has been around for a very long time and nobody was been concerned with the name being confusing so far.

**Comment by lgrapenthin** [comment]
@bbatsov I contributed this issue not to change the introduction text, but the title. Because the title is deceiving. 
Based on your input I'd suggest to call it:
- "Unofficial Community Clojure Style Guide"
Happy to open a new issue if necessary.
