### ISSUE TITLE
Consider updating/removing suggestions about complement, partial and comp

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/clojure-style-guide#233]
The guide currently features some suggestions like:

> Favor the use of  `complement` versus the use of an anonymous function.

There are similar guidelines about `comp` and `partial`. 

Recently someone asked about those on Slack and the general agreement was that they are not super common or provide any benefits over alternative approaches. Should we remove those guidelines or update their wording (e.g. the other way around)?

**Comment by danielcompton** [comment]
I think I feel the same way, especially with comp. Sometimes they're better, sometimes I think they make code harder to read; I wouldn't make a blanket recommendation for them.

**Comment by seancorfield** [comment]
Rich has said multiple times he thinks anonymous functions are more idiomatic than those others and I think he even said that he might omit those others if he did Clojure over?

So, yeah, I agree these recommendations in the guide are probably overreach or at least very subjective.

**Comment by manuel-uberti** [comment]
> I think I feel the same way, especially with comp. Sometimes they're better, sometimes I think they make code harder to read; I wouldn't make a blanket recommendation for them.

My line of thought exactly.

**Comment by bbatsov** [comment]
> Rich has said multiple times he thinks anonymous functions are more idiomatic than those others and I think he even said that he might omit those others if he did Clojure over?

I guess that's a good argument to flip the guidelines then.

**Comment by bbatsov** [comment]
There's a bit more on the topic here - https://ask.clojure.org/index.php/8373/when-should-prefer-comp-and-partial-to-anonymous-functions

**Comment by bbatsov** [comment]
I've updated the guidelines as discussed above.
