### ISSUE TITLE
cond-> and cond->> :always test expression

### ISSUE THREAD

**Issue by tomdl89** [bbatsov/clojure-style-guide#244]
I recently advised a clojure newcomer to use `:always` rather than `true` or `(constantly true)` to force threading in a `cond->>` expression. However, I realised that this is not mentioned in the style guide. I've seen it used quite widely across a number of code bases, so I'm fairly sure I'm not just imagining it - it _is_ the most common idiom. I'm happy to open a PR if so. The example would look something like this:
```
;; bad
(cond->> 42
  (= x 1) inc
  true (/ 99)
  (= y 2) dec)

;; good
(cond->> 42
  (= x 1) inc
  :always (/ 99)
  (= y 2) dec)
```
probably to follow the [Default cond Branch](https://github.com/bbatsov/clojure-style-guide#else-keyword-in-cond) section.

**Comment by seancorfield** [comment]
I just surveyed our codebase at work -- 142K lines of Clojure written over a decade or so.

* 443 `cond->`/`cond->>` expressions
* 14 use `:always`
* about 20 or so use `true`
* 3 use some other keyword that makes sense in context

I will say that most uses of `true` seem to be in older code and more modern code uses `:always` but I think, overall, that mixing contexts in a threaded pipeline is more of a smell than whether `true` or `:always` is used so I'm not sure this warrants an entry in the style guide (but I don't feel strongly about it either way).

https://stuartsierra.com/2018/07/06/threading-with-style has good advice about this -- and specifically says "don't thread arithmetic" so those would be poor examples according to that guidance anyway.

**Comment by bbatsov** [comment]
> I will say that most uses of true seem to be in older code and more modern code uses :always but I think, overall, that mixing contexts in a threaded pipeline is more of a smell than whether true or :always is used so I'm not sure this warrants an entry in the style guide (but I don't feel strongly about it either way).

Same sentiment here. 

> https://stuartsierra.com/2018/07/06/threading-with-style has good advice about this -- and specifically says "don't thread arithmetic" so those would be poor examples according to that guidance anyway.

I agree. I guess we should adapt Stuart's guideline for our guide.

**Comment by seancorfield** [comment]
I don't think the OP's proposal has sufficient consensus in the large to be worth adding to the Guide. I would like to see some of Sandra's guidelines around threading added into the Guide so I'd welcome a PR for that.

**Comment by bbatsov** [comment]
Sandra's or Stuart's? 😄

**Comment by seancorfield** [comment]
See https://www.lambdasierra.com/2022/hello

**Comment by bbatsov** [comment]
My bad - I had totally missed this article. Thanks for sharing!
