### ISSUE TITLE
Idiomatic namespace alias for clojure.spec.alpha should be `s` instead of `spec`

### ISSUE THREAD

**Issue by sheluchin** [bbatsov/clojure-style-guide#245]
All of the [official documentation](https://clojure.org/guides/spec) uses `s` as the namespace alias for `clojure.spec.alpha` but the style guide's [Use Idiomatic Namespace Aliases](https://github.com/bbatsov/clojure-style-guide#use-idiomatic-namespace-aliases) section suggests to use `spec` instead. Is there a reason for diverging from the official docs or is this a bug in the style guide?

**Comment by seancorfield** [comment]
I totally agree: `s` is far more idiomatic here. I think that section could be cleaned up a lot. It's widely considered idiomatic to alias namespaces to the last segment (if that is unique), and then a handful have common shorter aliases - so a lot of tired in that table could be removed.

I might have time to put together a PR for discussion tomorrow.

**Comment by seancorfield** [comment]
(I found a bit of time today for a PR for discussion!)

**Comment by seancorfield** [comment]
The PR for this has been merged. I'm not sure what's required to get that published on the site.

**Comment by seancorfield** [comment]
Ah, it's automatic. I was just impatient.

**Comment by sheluchin** [comment]
Thanks very much, @seancorfield. Your PR adds much clarity and corrects the issue. 

I referenced your PR in a clj-kondo ticket about adding the community guideline aliases as a linter. It'll be nice to have community standards like this reinforced by the tooling once myself or someone else implements that ticket.
