### ISSUE TITLE
The link to "The Joy of Clojure" is dead.

### ISSUE THREAD

**Issue by is2ei** [bbatsov/clojure-style-guide#248]
It seems the link "http://www.joyofclojure.com/" in "README.adoc" is dead.
<img width="1346" alt="Screenshot 2023-01-31 at 10 58 28" src="https://user-images.githubusercontent.com/3948353/215640351-1646f1de-bbba-42d9-86e4-a7c70c6c3d79.png">

It might be related to the removal of Heroku free plan.
https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

I'm not sure but "https://joyofclojure.github.io/" could be the alternative.

**Comment by seancorfield** [comment]
I ran into this recently while cleaning up https://clojure-doc.org -- but I hadn't found the github.io link so thanks for that.

**Comment by is2ei** [comment]
I agree with @seancorfield

**Comment by Chouser** [comment]
I think https://www.manning.com/books/the-joy-of-clojure-second-edition looks like a good choice, at least for now.
