### ISSUE TITLE
The link to "Clojure Programming" is dead

### ISSUE THREAD

**Issue by is2ei** [bbatsov/clojure-style-guide#250]
The link to "Clojure Programming" is dead.
<img width="953" alt="Screenshot 2023-01-31 at 16 14 09" src="https://user-images.githubusercontent.com/3948353/215691777-b80cc803-3061-42c2-95bf-6cf6d55fd1a1.png">

https://www.clojurebook.com/
<img width="1325" alt="Screenshot 2023-01-31 at 16 07 53" src="https://user-images.githubusercontent.com/3948353/215690512-242bad6f-83b7-4131-8847-519a476babd9.png">

I found the repository below and it seems the README contains the right URL.
https://github.com/clojurebook/ClojureProgramming

http://www.clojurebook.com/

<img width="1327" alt="Screenshot 2023-01-31 at 16 10 06" src="https://user-images.githubusercontent.com/3948353/215690955-418bc396-7e77-482d-a6fa-734a611ac587.png">

The domain "www.clojurebook.com" is alive but the site doesn't support SSL.

**Comment by seancorfield** [comment]
Thanks! I updated this directly on master since it was such a small change.
