### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by ildivan** [bbatsov/clojure-style-guide#252]
Hi, i am currently translating the guide in italian , i'm about 600 lines in and i was wondering if it was possible to add mine to the  list of translations, doesn't matter to me if now or when i'm finished.
The translation is at https://github.com/ildivan/clojure-style-guide/blob/ita/README.adoc

**Comment by bbatsov** [comment]
Sure. Feel free to submit a PR that mentions it.
